
export class Student {
    public student_rcd :string   
	public student_name :string   
	public student_nationality :string   
	public student_nation :string   
	public student_religion :string   
	public student_countryside :string   
	public student_apartment_number :number      
	public student_health_insurance_code :string   
	public student_citizen_identity_card :string   
	public student_citizen_identity_card_date :string   
	public student_citizen_identity_card_place :string   
	public student_phone_home :string   
	public student_phone :string   
	public student_province_of_residence :string   
	public student_resident_district :string   
	public student_resident_ward :string   
	public student_address :string   
	public student_province_born :string   
	public student_district_born :string   
	public student_ward_born :string   
	public student_address_receive :string   
	public student_facebook_url :string   
	public student_card_photo :string   
	public citizen_identification_photo :string   
	public father_name :string   
	public father_year_of_birth :Date
	public father_nationality :string   
	public father_nation :string   
	public father_religion :string   
	public father_permanent_residence :string   
	public father_work :string   
	public father_phone_number :string   
	public mother_name :string   
	public mother_year_of_birth :Date
	public mother_nationality :string   
	public mother_nation :string   
	public mother_religion :string   
	public mother_permanent_residence :string   
	public mother_work :string   
	public mother_phone_number :string   
	public spouses_name :string   
	public spouses_nationality :string   
	public spouses_nation :string   
	public spouses_religion :string   
	public spouses_address :string   
	public spouses_work :string   
	public spouses_phone_number :string   
	public gender :string   
	public student_email :string   
	public class_id :string   
	public student_role :string   
	public student_status :string   
	public date_of_birth :string   
	public school_year :string   
	public degree_name :string   
	public specialization_name_VN :string   
	public major_name_VN :string   
	public priority_flag :number      
	public cv_path :string      
	public password :string   
	public active_flag :number      
	public created_by_user_id :string   
	public created_date_time :Date
	public lu_updated :Date
	public lu_user_id :string   
}